# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "Software architecture made simple"
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/koderizer/arc/releases/download/v0.0.1/arc_0.0.1_darwin_amd64.tar.gz"
    sha256 "d25967f9c7cc99e0765c9b47d668bcefc5166ac5b588cb185b80605557ded0fe"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/koderizer/arc/releases/download/v0.0.1/arc_0.0.1_linux_amd64.tar.gz"
      sha256 "1f2181d2c9f260a899692dbfdb46c8ae29be93d74efc52115345afb237cdea9b"
    end
  end

  def install
    bin.install "arcli"
  end
end
