# This file was generated by GoReleaser. DO NOT EDIT.
class Arcli < Formula
  desc "Software architecture made simple"
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/koderizer/arc/releases/download/v0.0.2/arc_0.0.2_darwin_amd64.tar.gz"
    sha256 "2c17a31fc17d4d32e41d922b4116e9e1f8771cbc585f3ffb3ea036ef6c400c61"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/koderizer/arc/releases/download/v0.0.2/arc_0.0.2_linux_amd64.tar.gz"
      sha256 "0b982e5b6385ffe1030bd1bf44230dd34551284370bbe04181c6fd354caf3449"
    end
  end

  def install
    bin.install "arcli"
  end
end
