# This file was generated by GoReleaser. DO NOT EDIT.
class Arcli < Formula
  desc "Software architecture made simple"
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/koderizer/arc/releases/download/v0.0.3/arc_0.0.3_darwin_amd64.tar.gz"
    sha256 "a8da1132d6e7a2c081dae9e985d708785f2a72aa1380b789a7dd107443ddfd6e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/koderizer/arc/releases/download/v0.0.3/arc_0.0.3_linux_amd64.tar.gz"
      sha256 "55694bfb4e52e6b40f56644aac50749644fee4c7c96441e496222b3bd5f616c5"
    end
  end

  def install
    bin.install "arcli"
  end
end
